blank_issues_enabled: false
contact_links:
  - name: Reddit Community
    url: https://www.reddit.com/r/WurstClient/
    about: For general discussion, support, memes, etc.
  - name: Contact Alexander
    url: https://www.wurstclient.net/contact/
    about: For anything that shouldn't be public.
